embed_assets: on

javascripts:
  common:
    - public/javascripts/vendor/jquery-ui-1.8.2.custom.min.js
    - public/javascripts/vendor/jquery.enumerable.js
    - public/javascripts/vendor/jquery.blockUI.js
    - public/javascripts/vendor/jquery.hoverIntent.js
    - public/javascripts/vendor/jquery.fieldtag.js
    - public/javascripts/vendor/jquery.Jcrop.js
    - public/javascripts/vendor/jquery.cookie.js
    - public/javascripts/vendor/highcharts/highcharts.src.js
    - public/javascripts/vendor/fancybox/jquery.fancybox-1.3.1.js
    - public/javascripts/replace.js
    - public/javascripts/geolocation.js
    - public/javascripts/application.js

stylesheets:
  widget:
    - public/stylesheets/widget.css

  common:
    - public/stylesheets/vendor/smoothness/jquery-ui-1.8.2.custom.css
    - public/stylesheets/vendor/jquery.Jcrop.css
    - public/stylesheets/vendor/fancybox/jquery.fancybox-1.3.1.css
    - public/stylesheets/vendor/blueprint/screen.css
    - public/stylesheets/vendor/blueprint/buttons/screen.css
    - public/stylesheets/master.css
    - public/stylesheets/interaction.css
    - public/stylesheets/menu.css
    - public/stylesheets/reports.css
    - public/stylesheets/politicians.css
    - public/stylesheets/causes.css
    - public/stylesheets/interest_groups.css
    - public/stylesheets/tag_cloud.css
    - public/stylesheets/guide.css
    - public/stylesheets/sprites.css
