embed_assets: on

javascripts:
  common:
    - public/javascripts/jquery-1.3.2.min.js
    - public/javascripts/jquery-ui-1.7.2.custom.min.js
    - public/javascripts/jquery.blockUI.js
    - public/javascripts/application.js

stylesheets:
  common:
    - public/stylesheets/compiled/screen.css
    - public/stylesheets/master.css
    - public/stylesheets/smoothness/jquery-ui-1.7.2.custom.css
