embed_assets: on

javascripts:
  common:
    - public/javascripts/vendor/jquery-ui-1.8.1.custom.min.js
    - public/javascripts/vendor/jquery.address-1.1.min.js
    - public/javascripts/vendor/jquery.blockUI.js
    - public/javascripts/vendor/jquery.hoverIntent.js
    - public/javascripts/vendor/jquery.fieldtag.js
    - public/javascripts/vendor/jquery.Jcrop.js
    - public/javascripts/vendor/jquery.qtip-1.0.0-rc3-dm.js
    - public/javascripts/vendor/jquery.qtip.preload.js
    - public/javascripts/vendor/highcharts.js
    - public/javascripts/replace.js
    - public/javascripts/qtip.js
    - public/javascripts/application.js

stylesheets:
  common:
    - public/stylesheets/stationary/reset.css
    - public/stylesheets/stationary/oldie.css
    - public/stylesheets/smoothness/jquery-ui-1.8.1.custom.css
    - public/stylesheets/master.css
    - public/stylesheets/interaction.css
    - public/stylesheets/menu.css
    - public/stylesheets/us.css
    - public/stylesheets/reports.css
    - public/stylesheets/interest_groups.css
    - public/stylesheets/tag_cloud.css
    - public/stylesheets/jquery.Jcrop.css
