<%
rerun = File.file?('rerun.txt') ? IO.read('rerun.txt') : ""
requires = "--require features/step_definitions --require features/support"
rerun_opts = rerun.to_s.strip.empty? ? "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} features" : "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} #{rerun}"
std_opts = "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} --strict --tags ~@wip"
%>
default: <%= requires %> <%= std_opts %> features
wip: <%= requires %> --tags @wip:3 --wip features
rerun: <%= requires %> <%= rerun_opts %> --format rerun --out rerun.txt --strict --tags ~@wip
