--- 
- :version: ">= 1.2.0"
  :name: ancestry
- :version: ">= 2.1.5"
  :name: Empact-authlogic
- :version: ">= 1.1.8"
  :name: Empact-authlogic_rpx
- :version: ">= 2.0.5"
  :name: bluecloth
- :name: declarative_authorization
- :version: ">= 2.0.3"
  :name: delayed_job
- :version: ">= 2.6.6"
  :name: erubis
- :name: excelsior
- :name: fastercsv
- :name: foreigner
- :version: ">= 3.0.6"
  :name: friendly_id
- :name: geokit
- :version: ">= 2.1.0"
  :name: gravtastic
- :version: ">= 2.3.2"
  :name: hoptoad_notifier
- :name: jammit
- :version: ">= 1.4.3"
  :name: json
- :name: loofah
- :version: ">= 2.6.0"
  :name: puppet
- :version: ">= 0.4.0"
  :name: shadow_puppet
- :version: ">= 1.0.4"
  :name: bson_ext
- :version: ">= 1.0.4"
  :name: bson
- :version: ">= 1.0.6"
  :name: mongo
- :version: ">= 0.8.2"
  :name: mongo_mapper
- :name: Empact-mongo_session_store
- :version: ">= 2.12.3"
  :name: newrelic_rpm
- :name: nokogiri
- :version: ">= 2.3.3"
  :name: paperclip
- :name: pg
- :version: ">= 0.6.12"
  :name: rpx_now
- :name: state_machine
- :name: spatial_adapter
- :version: = 0.10.8
  :name: sunspot
- :version: = 0.11.5
  :name: sunspot_rails
- :source: http://gems.github.com
  :name: polly-suppress_validations
- :name: tamtam
- :name: typhoeus
- :version: ">= 0.3.3"
  :name: votesmart
- :version: ">= 2.3.14"
  :name: Empact-will_paginate
- :name: ym4r
- :name: httparty
- :name: parallel
- :name: scout
- :name: request-log-analyzer
- :version: 2.3.9
  :name: rails
