--- 
- :version: ">= 1.2.0"
  :name: ancestry
- :version: ">= 2.1.5"
  :name: Empact-authlogic
- :version: ">= 1.1.8"
  :name: Empact-authlogic_rpx
- :version: ">= 2.0.5"
  :name: bluecloth
- :name: declarative_authorization
- :version: ">= 2.0.3"
  :name: delayed_job
- :name: erubis
- :name: excelsior
- :name: fastercsv
- :version: = 1.0.71
  :name: facebooker
- :version: ">= 3.0.6"
  :name: friendly_id
- :name: geokit
- :version: ">= 2.1.0"
  :name: gravtastic
- :name: hoptoad_notifier
- :name: jammit
- :version: ">= 1.4.3"
  :name: json
- :name: shadow_puppet
- :version: = 1.0.0
  :name: bson_ext
- :version: = 1.0.0
  :name: bson
- :version: = 1.0.0
  :name: mongo
- :version: ">= 0.7.6"
  :name: mongo_mapper
- :name: Empact-mongo_session_store
- :version: ">= 2.11.2"
  :name: newrelic_rpm
- :name: nokogiri
- :name: paperclip
- :name: pg
- :version: ">= 0.6.12"
  :name: rpx_now
- :name: state_machine
- :name: spatial_adapter
- :version: = 0.10.8
  :name: sunspot
- :version: = 0.11.5
  :name: sunspot_rails
- :source: http://gems.github.com
  :name: polly-suppress_validations
- :version: ">= 0.3.0"
  :name: votesmart
- :version: ">= 2.3.14"
  :name: will_paginate
- :name: ym4r
- :name: httparty
- :name: parallel
- :name: auto_tagger
- :version: 2.3.8
  :name: rails
