development: &global_settings
  morphology: stem_en
  enable_star: true
  min_infix_len: 3

test:
  <<: *global_settings

staging:
  <<: *global_settings

production:
  config_file: "RAILS_ROOT/config/ENVIRONMENT.sphinx.conf"
  searchd_log_file: "RAILS_ROOT/log/searchd.log"
  query_log_file: "RAILS_ROOT/log/searchd.query.log"
  pid_file: "/srv/vote-reports/shared/pids/searchd.pid"
  <<: *global_settings
